### ISSUE TITLE
Feature/Bug: Contrast between Active and Hover state is not sufficient 

### ISSUE THREAD

**Issue by synnaf** [Frojd/Frojd-Jewl#5]
The contrast value between active and hover-state is not sufficient to pass. We should be able to write a function that generates a more accessible color?  Maybe something similar to this: https://css-tricks.com/programming-sass-to-create-accessible-color-combinations/ 

https://github.com/Frojd/Frojd-Jewl/blob/f22b4ee1d7b15e2ba7c0761777ebd8756dcd90d9/component-library/app/components/Button/Button.module.scss#L104

**Comment by saraojelind** [comment]
@synnaf This is more a question for the design of buttons, and since we only implement the desired hover state from the design, I don't think a function in scss will be usable. Do you have an example for a more accessible hover-state? If we can define what criterias that should be met to achieve an accessible hover-state, then it is something we can pass on to the design instead.

**Comment by synnaf** [comment]
I'll pass it on to design and add their response in this issue!

**Comment by synnaf** [comment]
Issue have been researched and discussed with design.
